WB-5
Discord-Dutch-HypeSquad/Watson-Bot pull request #2
Opened 2017-07-24 09:59 UTC by duncte123

Create the command system and add two commands

2017-07-25 07:45 UTC, kevzz1994 requested changes

2017-07-25 07:45 UTC, KSchaap commented on src/main/java/io/hypesquad/watsonbot/event/WatsonEventListener.java
> +        //Handle command
This can be done much easier. Find a better and more logical way.

2017-07-27 19:07 UTC, KSchaap commented on src/main/java/io/hypesquad/watsonbot/commands/AbstractWatsonCommand.java
> +     * @return ture if checks pass, false otherwise
Quite the typo you have there.

2017-07-27 19:07 UTC, cascer1 commented on src/main/java/io/hypesquad/watsonbot/commands/AbstractWatsonCommand.java
> +     * @return ture if checks pass, false otherwise
fffffff

2017-07-27 19:13 UTC, cascer1 submitted a review, later dismissed

2017-07-27 19:40 UTC, kevzz1994 requested changes

2017-07-27 19:40 UTC, KSchaap commented on src/main/java/io/hypesquad/watsonbot/commands/WatsonHelpCommand.java
> +        final StringBuilder stringBuilder = new StringBuilder(80).append("```\n");
Why ``80``?

2017-07-28 11:58 UTC, kevzz1994 requested changes

2017-07-28 11:58 UTC, KSchaap commented on src/main/java/io/hypesquad/watsonbot/commands/WatsonHelpCommand.java
> +        final StringBuilder stringBuilder = new StringBuilder(20).append("```\n");
``new StringBuilder(20)``, 20 here is a magic number. Refactor to a constant.

2017-07-29 17:44 UTC, kevzz1994 requested changes

2017-07-29 17:44 UTC, KSchaap commented on src/main/java/io/hypesquad/watsonbot/commands/AbstractWatsonCommand.java
> +        return 1;
Hashcode should be calculated differently.

2017-07-29 17:57 UTC, kevzz1994 approved these changes

2017-07-29 18:00 UTC, merged